apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: banking-app-staging

resources:
  - ../../base

replicas:
  - name: banking-app
    count: 2

patchesStrategicMerge:
  - patch-deployment.yaml

commonLabels:
  environment: staging
  app.kubernetes.io/version: "1.0.0"

images:
  - name: tdksoft341/tdk-banking-app
    newTag: "develop-b2590436"
  - name: redis
    newTag: "develop-b2590436"