apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
  name: banking-app
spec:
  replicas: 2
  namespace: banking-app-staging
spec:
  template:
    spec:
      containers:
        - name: banking-app
          env:
            - name: ALLOWED_HOSTS
              value: "banking.staging.votredomaine.com,localhost,127.0.0.1,.votredomaine.com, *.tdk.com, *"
