apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-app
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: banking-app
          env:
            - name: ALLOWED_HOSTS
              value: "*,localhost,127.0.0.1"
