apiVersion: v1
kind: Secret
metadata:
  name: banking-app-secrets
  namespace: banking-app-prod
  labels:
    app.kubernetes.io/name: banking-app
type: Opaque
data:
  # Remplacez par vos valeurs encodées en base64
  SECRET_KEY: "base64-encoded-secret-key-here"
  DATABASE_URL: "base64-encoded-database-url-here"