apiVersion: v1
kind: Service
metadata:
  name: banking-app-service
  labels:
    app.kubernetes.io/name: banking-app
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: banking-system
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8000
    targetPort: http-app
    protocol: TCP
  - name: metrics
    port: 8080
    targetPort: http-metrics
    protocol: TCP
  selector:
    app.kubernetes.io/name: banking-app
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    app.kubernetes.io/name: banking-app
    app.kubernetes.io/component: redis
    app.kubernetes.io/part-of: banking-system
spec:
  type: ClusterIP
  ports:
  - name: redis
    port: 6379
    targetPort: redis
    protocol: TCP
  selector:
    app.kubernetes.io/name: banking-app
---
apiVersion: v1
kind: Service
metadata:
  name: banking-app-metrics
  labels:
    app.kubernetes.io/name: banking-app
    app.kubernetes.io/component: metrics
    app.kubernetes.io/part-of: banking-system
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: http-metrics
    protocol: TCP
  selector:
    app.kubernetes.io/name: banking-app