apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: banking-app-prod

resources:
- ../../base

replicas:
- name: banking-app
  count: 3

patchesStrategicMerge:
- patch-deployment.yaml

commonLabels:
  environment: production
  app.kubernetes.io/version: v1.0.0

images:
- name: tdksoft341/tdk-banking-app
  newTag: v1.0.0