apiVersion: v1
kind: Secret
metadata:
  name: banking-app-secrets
  namespace: banking-app-prod
type: Opaque
data:
  # echo -n 'votre-secret-key-production' | base64
  SECRET_KEY: eW91ci1zZWNyZXQta2V5LXByb2R1Y3Rpb24=
  # echo -n 'sqlite:///db.sqlite3' | base64
  DATABASE_URL: c3FsaXRlOi8vL2RiLnNxbGl0ZTM=