apiVersion: v1
kind: Secret
metadata:
  name: banking-app-secrets
  namespace: banking-app
type: Opaque
data:
  # echo -n 'your-secret-key' | base64
  SECRET_KEY: eW91ci1zZWNyZXQta2V5
  # echo -n 'postgresql://user:pass@postgres:5432/bankdb' | base64
  DATABASE_URL: cG9zdGdyZXNxbDovL3VzZXI6cGFzc0Bwb3N0Z3Jlczo1NDMyL2JhbmtkYg==